### ISSUE TITLE
Cant include SDL_gpu.

### ISSUE THREAD

**Issue by nextdimension** [grimfang4/sdl-gpu#114]
Its confusing. I have usr/include/SDL2/SDL.h  in my path. SDL-GPU is added to system under usr/local/include/SDL2/SDL_gpu.h after running makefile and it includes <SDL.h>  in the header file which is obviously wrong as SDL is not at that path. How can I get this to work without modifying the header files?

**Comment by edomin** [comment]
I using extra -I compiler flag with path to SDL.h

**Comment by grimfang4** [comment]
Using <SDL.h> means it will look in standard compiler paths for SDL.h.  I'm not sure about what happens if a *file* is in your path, but if usr/include/SDL2 is in your path, then it should work.  If something is still up, try edomin's suggestion of adding an explicit -I/usr/include/SDL2 (that's a capital i).
