### ISSUE TITLE
Multiple Window problems

### ISSUE THREAD

**Issue by masonwheeler** [grimfang4/sdl-gpu#12]
SDL2 has excellent support for multiple windows, but SDL_GPU is a bit schizophrenic on the subject.  On one hand, it appears to assume that only one window will exist:
- Library initialization is conflated with window creation
- After `Init` runs, `GPU_GetInitWindow()` is guaranteed to return a valid window ID, which will interfere with attempts to `Init` a second window.
- There is no `DestroyWindow` API distinct from `GPU_Quit`

But on the other hand, we have `GPU_MakeCurrent`, which is only useful if you have more than one window.

**Comment by grimfang4** [comment]
Windowing is in a sad state at the moment.  SDL_gpu seems schizophrenic for two reasons: It supports both SDL 1.2 and 2.0, and I haven't sat down to work out the window/target memory semantics.

Right now, context targets need to have a window associated with them.  There is an internal mapping as well (used by GPU_GetWindowTarget() to make event handling reasonable) that may (in the future) be used to destroy the window when the target is freed, if the target owns the window.  Of course this implies that ownership semantics need to be added.

SDL_gpu does not currently free any window (even the one it creates... :-/) and only creates one when you don't specify an init window.  Beside that, you would use SDL's own window management functions (with the SDL_WINDOW_OPENGL flag) and associate the window with a target either by creating one with GPU_CreateTargetFromWindow() or remap an existing target with GPU_MakeCurrent().

I haven't thought about initing SDL_gpu twice, so there's not even a check on that.  I would make that a no-op counter instead of letting it reinitialize and create another window.  I'd like to defer to SDL's window APIs as much as possible.

**Comment by masonwheeler** [comment]
Hmm.  What's the rationale for continuing to support SDL 1.2 when even the SDL team no longer supports SDL 1.2?  The obvious downside is massively increased complexity.  (And a few bugs.  For example, CMake fails to correctly add the `SDL_GPU_USE_SDL2` define to a generated Visual Studio project file.)

**Comment by grimfang4** [comment]
Mostly historical, but people (including some specific users of SDL_gpu) do still use SDL 1.2 even though I'm with you and I think they shouldn't.  The added complexity is bad, but it hasn't as of yet been an actual problem.  Compatibility was a big feature for me in the early days of SDL_gpu because I wanted to port my games to SDL 2 and I hesitate to break that because it is a loss of a feature that SDL_Renderer doesn't have.

**Comment by grimfang4** [comment]
Multiple window support has been much improved as of df0f6d81238e32f0e3006c75e258757e89c3bbd9.
