### ISSUE TITLE
GPU_BlitRect is very inefficient

### ISSUE THREAD

**Issue by incinirate** [grimfang4/sdl-gpu#144]
Hi, I'm not sure if this is a good place to put this, but I've noticed that using GPU_BlitRect is very inefficient compared to GPU_Blit. When running with GPU_Blit, my game uses around 5-6% of my cpu actively, however, switching to BlitRect (passing NULL for src and target to scale them properly) brings up usage to around 25% cpu actively. I assume this is because the processor has to write extra pixels into the target as it scales up the image. Bottom line question, Is there any way for me to do this scaling on the gpu?

**Comment by grimfang4** [comment]
I'm not seeing this effect clearly in my tests.  Can you provide a test case that does it to you?

There are some potential extra CPU calculations done in GPU_BlitRect() because it shares the codepath of GPU_BlitRotate() and such, but it does use the GPU for filling, so the real scaling work is still being done on the GPU.

**Comment by incinirate** [comment]
Here is a Gist that demonstrates this behavior:
https://gist.github.com/incinirate/9ea87131e5e27ef056a98bbeca505328

Press any key other than escape to switch between normal Blit and BlitScale.

**Comment by incinirate** [comment]
After further testing it appears this was actually just an issue with my environment. Sorry to bother you.
