### ISSUE TITLE
Emscripten context creating issues

### ISSUE THREAD

**Issue by egordorichev** [grimfang4/sdl-gpu#150]
Hi, I've been using your awesome lib quite for a while, thanks so much for writing it. 
Tho I found a small issue, when I tried to compile my app for emscripten: 

_I dont think this matters, but just in case, here is how I compiled it_
```
em++ -lm -s USE_WEBGL2=1 -s FULL_ES3=1 -std=c++1z src/web.cpp src/tsab.cpp libs/glew.o    libs/Lua/*.o libs/SDL_GPU/*.o libs/stb_*.c -I src/  -I libs/include -I libs/include/Lua/ -I libs/include/SDL_GPU/  -o index.html -s USE_SDL=2 -s USE_SDL_TTF=2 -s USE_SDL_IMAGE=2 -s LEGACY_GL_EMULATION=1 -o2 --preload-file config.lua --preload-file default.frag --preload-file font.ttf --preload-file api.lua --preload-file main.lua --preload-file gamecontrollerdb.txt --emrun -s WASM=0 && emrun ./index.html
```

I had a general issue with creating an opengl context in the browser, but I figured out, that if I place those lines before my SDL_Init:

```c++
	SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 3);
	SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 0);
	SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_ES);
	SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_CORE);
	SDL_GL_SetAttribute(SDL_GL_DOUBLEBUFFER, 1);
	
	SDL_Init(SDL_INIT_EVERYTHING);
        // Create window
```

Then I can create an opengl context just fine:

```c++
	SDL_GLContext context = SDL_GL_CreateContext(window);
        // Not NULL!
```

But I couldn't get sdl_gpu creating it in any way, I've even modified its source, yet I still get the same result:

```
WARNING: using emscripten GL immediate mode emulation. This is very limited in what it supports
size 512:512
OPEN GL VERSION 4 0
GPU_InitRendererByID: BACKEND ERROR - Renderer OpenGL 4 failed to initialize properly
OPEN GL VERSION 3 0
GPU_InitRendererByID: BACKEND ERROR - Renderer OpenGL 3 failed to initialize properly
OPEN GL VERSION 2 0
GPU_InitRendererByID: BACKEND ERROR - Renderer OpenGL 2 failed to initialize properly
OPEN GL VERSION 1 1
NULL CONTEXT TARGET
```

_The version debug was added by me_

```
uname -a
Linux rexcellentgames.com 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

Testing everything on google chrome. Using most of SDL2 libs, except net and audio. 

Thanks again for your awesome lib, and I hope that the issue isn't too deep, Egor.

**Comment by albertvaka** [comment]
- WebGL 1 and 2 are roughly equivalent to OpenGL ES 2 and 3. SDL-GPU won't be able to start other OpenGL renderers since they don't work on WebGL. For this reason, you better disable them at compile time with `-DSDL_GPU_DISABLE_OPENGL=1 -DSDL_GPU_DISABLE_GLES_1=1`
- You probably don't need to `SDL_GL_SetAttribute`, tp let SDL initialize whatever it can depending on the platform. Also, you are setting `SDL_GL_CONTEXT_PROFILE_CORE` after `SDL_GL_CONTEXT_PROFILE_ES` which I think overrides the first. As I said, WebGL is similar to ES, so forcing `SDL_GL_CONTEXT_PROFILE_CORE` might prevent initializing OpenGL ES.
- `FULL_ES3=1` enables software emulation of the features in OpenGL ES 3 that aren't available on WebGL 2, instead of failing the build. Emulated features are slow. Unless you really need it, keep it disabled.
