### ISSUE TITLE
is there win32/x86 support? (couldn't find any info anywhere)

### ISSUE THREAD

**Issue by idbxy** [grimfang4/sdl-gpu#187]
Hi, 

It has been a big hassle to make it work on windows (with visual studio 2019)
, hell I didn't even make it work, I just found a project that used sdl_gpu with an sln file in the repository and am testing that, but I saw there is only x64 compiler options, so I was wondering is it due sdl_gpu not supporting x86? 

thank you

**Comment by grimfang4** [comment]
Hi,

Yes, SDL_gpu works with x86.  That's actually the primary architecture I build for personally.  I have kept the CMake build up to date.  You can use that to generate Visual Studio projects.

The build system is getting some work done next to update the other standard build tools, and I'll be putting more time into getting build artifacts deployed from the automated builds.  In the meantime, here's an older x86 build: http://dinomage.com/open/SDL2_gpu-0.11.0-msvc-x86.zip

**Comment by idbxy** [comment]
hey! I already tried generating visual studio projects with cmake, but I couldn't get it to work, however I'm not experienced in cmake at all. 

I saw today that you added build artifacts, and will try that first thing tomorrow! I'm excited ^^. 

Thanks for answering my question,

I have one more thing,

I'm trying to render the render in an imgui window, which I succeeded in, but I have no idea how not to render it to the window, and only in the dear imgui window, would you be so kind to maybe steer me in the right direction?

So right now i'm doing in my render loop the following: 
`GPU_Image* image = GPU_CopyImageFromTarget( mainWindow->GetTarget() );`

to create an image from the target (I know I don't have to create a new image every frame, but it's for clarity)

however I have no idea how to init an sdl window, and not render to it, but still have my rendered target to create an image to pass it along dear imgui

any idea?

**Comment by idbxy** [comment]
@grimfang4 another quick question, do you still use sdl_ttf for text rendering with sdl_gpu or how should this be approached now?

**Comment by grimfang4** [comment]
I'm not sure about imgui, as I haven't used it.  It sounds like you have two windows.  To avoid that, you can create the window using SDL, then choose the window that SDL_gpu will use with GPU_SetInitWindow().  If that's not helpful, let me know more details or share some code and I can help further.

I do use SDL_ttf.  You can render to an SDL_Surface and copy that into a GPU_Image.  However, for convenience and efficiency, I use another of my libraries instead of SDL_ttf directly (SDL_FontCache for C or NFont for C++).

I don't think I have an open source game handy, but there are demos and tests in the SDL_gpu repository that are good to look at.  SDL_gpu's normal batching is automatic.  It just collects the geometry from your draw requests, ignores redundant state changes, and submits them all at once for rendering.

I can dig up a project and open source it, if you want.  I'm also planning on making a new project for a tutorial series after I've published the upcoming SDL_gpu 1.0.0.

**Comment by idbxy** [comment]
Hi, 

about imgui, what I want to achieve is this: https://gamedev.stackexchange.com/questions/150214/render-in-a-imgui-window
but with sdl_gpu, and I'm having a hard time figuring it out how. 

currently I am able to render into the imgui window, but it also renders to the sdl_window/sdl_gpu window and I have no idea how to not do that, but do render to imgui window

the link also provides source code that could help you understand what I want to achieve


I would love to see a project from yours how you used sdl_gpu. So I can use it as reference for whenever I'm stuck.

Oooh, what's different from the latest version and sdl_gpu 1.0.0?

**Comment by idbxy** [comment]
@grimfang4 to add to the previous message, it seems like I need to render to a framebuffer, not draw it on the window, and use that "render" in an imgui window, but I can't seem to figure out how to do it at all, been trying for 3 days already trying all various things and searching.

**Comment by idbxy** [comment]
Hi, update 3 

I found a temporary? solution, but i'm not sure how much of an issue this is performance wise?

Basically i'm saving an image from the target, than clearing the window and sending the image off to imgui

so basically my window will render just black, and the imgui window will be the actual render

i'm basically trying to create an editor for my engine i'm creating through the use of imgui and have a draggable screen

if you know how to do this in a better, more optimized way, please do let me know
```
void Game::Render()
{
	GPU_ClearRGBA( target1 , 0 , 0 , 0 , 255 );

	entityManager.Draw();

	GPU_FlushBlitBuffer();

	m_image = GPU_CopyImageFromTarget( mainWindow->GetTarget() );
	//clear the window again?
	GPU_ClearRGBA( target1 , 0 , 0 , 0 , 255 );
	//render the created image
	gui.OnImGuiRender( m_image );
	//flip
	GPU_Flip( target1 );
}
```

**Comment by idbxy** [comment]
@grimfang4 hi, do you have time any time soon to help me out with the above? it's a matter of if im going to use sdl_gpu for my school project or not

thanks ^^

**Comment by grimfang4** [comment]
Is there a place you can post the full code and project or a minimal reproduction?  That would help to see how you're setting up the window and all the rendering details.

If you want to render to an image/texture instead of copying a target every frame, then create the image first, (e.g. with GPU_CreateImage()) then call GPU_LoadTarget() on it once.  You can then use image->target as the destination for rendering and pass the image to imgui.

**Comment by idbxy** [comment]
Hey, I managed to get it to work the way you said , thanks ^^.
