### ISSUE TITLE
when stbi is found, but stbi_write isn't, the include path for bundled stbi is missing

### ISSUE THREAD

**Issue by timo** [grimfang4/sdl-gpu#19]
here's a super hacky fix. when only one of the two is missing, the system-wide one that was found shouldn't be used and i don't know anything about cmake to kick the system-wide one out if stbi_write isn't there.

```patch
diff --git a/CMakeLists.txt b/CMakeLists.txt
index be0fe38..5eadd1f 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -235,11 +235,10 @@ if(NOT GLEW_FOUND)
   include_directories(src/externals/glew/GL)
 endif(NOT GLEW_FOUND)
 
-if(NOT STBI_FOUND)
+if(NOT STBI_FOUND OR NOT STBI_WRITE_FOUND)
   include_directories(src/externals/stb_image)
   add_definitions("-DSTBI_FAILURE_USERMSG")
-endif(NOT STBI_FOUND)
-
+endif(NOT STBI_FOUND OR NOT STBI_WRITE_FOUND)
 
 add_definitions("-Wall -std=c99 -pedantic")
 
```

**Comment by grimfang4** [comment]
Thanks for pointing this out!  There shouldn't be a problem with mixing stb-image and stb-image-write, so I assume this is because of conflicting headers when one is bundled and both are added to the include path?  I moved stb-image-write into its own directory so this should be fixed in 7e202a3f168bb6318dd1f9fb8d2b8b44bebdf11c.
