### ISSUE TITLE
Documentation for GPU_Flip

### ISSUE THREAD

**Issue by Abestanis** [grimfang4/sdl-gpu#27]
I am in the process of updating a project from SDL2 to SDL_gpu and I encountered some strange behavior:
The content of my GPU_Images are drawn to the window, even though they are supposed to be off-screen drawables.
After digging trough the source code of SDL_gpu I believe that this is caused by the GPU_Flip function.

I used the GPU_Flip function to replace all occurrences of SDL_RenderPresent, as it is suggested in the "Conversion" section in your README. When I used SDL_RenderPresent on my off-screen drawables, they where not drawn on the window.

If it is intended for GPU_Flip draw the content of a GPU_Image to the screen, please document that behavior so others won't make the same mistake as I did.

**Comment by grimfang4** [comment]
SDL_RenderPresent's documentation doesn't make this use-case very clear either.  GPU_Flip() is not necessary for render-to-texture, but it should still be okay to call it.  So this is more than just a documentation bug.  In 26bc4111f74539c5fb54f11e26fb9fdfbe66be85, I have added a check to GPU_Flip() so that it should work as expected for rendering to texture.

**Comment by Abestanis** [comment]
The fix works, the GPU_Images are not drawn to the screen anymore by GPU_Flip.
Thanks for the fast fix!
