### ISSUE TITLE
Rendering to Framebuffers?

### ISSUE THREAD

**Issue by mmontag** [grimfang4/sdl-gpu#36]
Hi, I'm trying to follow the tutorial over here https://open.gl/framebuffers to achieve some post processing in combination with sdl-gpu.  I am just rendering to a framebuffer connected to a texture, and then trying to render the texture to a quad. So I call `glBindFramebuffer` to switch to the offscreen framebuffer.

I can't my quad with the framebuffer texture to show up when I switch back to the onscreen framebuffer. I was just wondering if this is a limitation of sdl-gpu before I continue.

To provide more context, I am simply trying to render an entire scene, including shader output, at 320x240, and then scale it up 3x with nearest-neighbor sampling for a retro-style game. Maybe there is an easier way to accomplish this.

**Comment by grimfang4** [comment]
This should be fine.  Have you looked at the 3d demo for SDL_gpu?  If you are trying to combine OpenGL and SDL_gpu rendering, there are some steps to take for resetting SDL_gpu's state.

Alternatively, if your scene is 2d, you can do it all in SDL_gpu with offscreen rendering and shaders.  You can create offscreen targets with GPU_CreateImage() and GPU_LoadTarget().  I should make a simple shader demo to help show this, since it is a pretty common use for SDL_gpu.

**Comment by grimfang4** [comment]
If you are stuck, send me some code and I'll let you know if I see anything.

**Comment by mmontag** [comment]
Yes, I started by copying some code from the 3d demo.

The scene is 2d, but I want to combine with some basic 3d polygon rendering, so that's why I turned to SDL_gpu. 

What would be amazing is just a demo of how to use framebuffers with SDL_gpu, either rendering to a texture or accomplishing a post-processing effect like Gaussian blur. 

My code is a huge mess, combining your 3d demo with the open.gl/framebuffers demo, but here's a link: http://d.pr/f/Aq2n 😅

**Comment by mmontag** [comment]
Hey, I figured out my issue - I switched from GLSL 120 to 150, and needed to modify the 3d demo to bind to a vertex array object.  Then it was a matter of calling `glUseProgram` and `glBindVertexArray` before everything else in the draw triangles function.
