### ISSUE TITLE
Build in Windows Error

### ISSUE THREAD

**Issue by xgibbousx** [grimfang4/sdl-gpu#39]
Hello,

I am doing the following process:

1. Cloning sdl-gpu git repo to my Desktop using cmd.exe (command prompt) with admin access.
2. Running: cmake -G "MinGW Makefiles"
3. Running: mingw32-make

I get some warnings like:
1. "cast to pointer from integer of different size" 
2. "CMakeFiles\SDL_gpu_shared.dir/objects.a(renderer_OpenGL_4.c.obj):renderer_OpenGL_4.c:(.text+0xd947): undefined reference to `SDL_free'"

Finally, I get some errors like:
1. "collect2.exe: error: ld returned 1 exit status"
2. "src/libSDL2_gpu.dll failed"
3. "mingw32-make[2]: *** [src/libSDL2_gpu.dll] Error 1"
4. "mingw32-make[1]: *** [src/CMakeFiles/SDL_gpu_shared.dir/all] Error 2"

At the end of it all, "src/libSDL2_gpu.dll.a" is created but "libSDL2_gpu.dll" is not.

My questions are as follows:
1. How can I properly build sdl-gpu on Windows?
2. Are the errors and warnings I am getting normal?
3. Don't I need the actual .dll to use after building my project with sdl-gpu or just the .a file?

Thanks so much for any help you can provide.

**Comment by grimfang4** [comment]
The "undefined reference" error is saying that some SDL function hasn't been linked.  That usually means that SDL itself is not being linked (happens often when setting up a new project) or that the SDL headers and SDL library have mismatched versions (this is not common).

The other errors say that the SDL_gpu dll couldn't be created because of that linking error.

1. You need to double-check that the paths to SDL are right.  You'll need to regenerate the make files after doing so.  Look in CMakeCache.txt and you can set them manually before running cmake again.  I personally use CMake-gui on Windows, which is kinda messy but makes it a little easier to figure out which paths need to be fixed and fix them.  I also use the Code::Blocks generator because I'm comfortable in that IDE.

2. These errors are common, but not normal.  If you do make it work, please describe the steps you took so we can help improve things.

3. You do need the .dll.  The .a file is the import library, which lists the symbols that will be found in the dynamic library, libSDL_gpu.dll.  The .a is what you link to when you build your own project/game.  When you run your game, it will then try to link to the .dll before it starts.  If it can't find the .dll (usually in the same directory as the executable), then it will fail with a message to that effect.  In other words, both the .a and the .dll are necessary.

**Comment by xgibbousx** [comment]
Hi Grimfang,

Thanks so much for your detailed answer.

I tried the exact same build process on my work laptop today and everything worked perfectly.  Very odd because the environments between my home and work laptop are almost identical. 

I was able to integrate SDL_gpu into my project files (header includes and linking) and tested a build with the "GPU_SetDebugLevel(GPU_DEBUG_LEVEL_MAX);" command and everything builds perfectly.  I also placed the .dll in my build folder, for the runtime to access, and everything also works perfectly.  This is all great news.

All of the paths to SDL are correct at home.  I am going to do more testing at home tonight and try to isolate the issue specific to that computer.  I will update you here once I find the problem so that others might be helped by it.

**Comment by xgibbousx** [comment]
I have continued to try and find why my home computer won't link to the SDL library during the "mingw32-make" process.  I have tried the following:

1. Uninstall and reinstall cmake.
2. Install the latest versions of the SDL library into my MinGW directory.
3. Check the paths to SDL to ensure they are correct in cmake.
4. Point to the SDL library files located in a different directory (e.g. Downloads folder with the latest file versions there) to ensure there are no odd permission conflicts.
5. Make sure everything is being run as administrator including cmd.exe and cmake.exe.
6. Edit the CMakeCache.txt file and change the direction of the slashes in the paths pointing to the SDL library.  This resulted in a file not found error which means the other paths are correct.

The only thing I haven't done is completely reinstall MinGW because it's kind of lengthy.  The good news is that I was able to get the library files built on my work computer and they work properly at home.

The only thing I can determine is that somehow my compiler (GCC g++ I assume) is refusing to link to SDL when running through the makefile process.  I am able to build with the same compiler in my IDE (Eclipse CDT) without issue.

Is there a way to debug this?  For example, is there a way for me to see the exact g++ command that is trying to be run?

That way, I could at least test just that one command and see if it is being formed properly.

The great news is that I should be able to start developing with the sdl-gpu library I built at work.  I will leave this open in case people have other suggestions or I find a solution myself.

**Comment by grimfang4** [comment]
I haven't tried this, but supposedly there's a verbosity setting in the makefiles that CMake generates:
mingw32-make.exe VERBOSE=1

**Comment by xgibbousx** [comment]
Finally figured it out!

SDL-GPU was compiling using g++ in my C:\TDD-GCC-64 folder.  Instead, it needed to use g++ in C:\MinGW\bin.

In order to make this happen, you simply have to remove C:\TDD-GCC-64 from your PATH environment variables and make sure that C:\MinGW\bin is still in your PATH environment variables.  CMake will automatically determine that the only g++ is available in C:\MinGW\bin since it apparently uses your PATH environment variables to determine this.

I also tried to compile with C:\TDD-GCC-32 which also didn't work.  Therefore, only g++ in C:\MinGW\bin will work.

Hope this helps someone else.
